In [8]:
import numpy as np
import random
import os


In [2]:
def FillMatrix(mat):
    for x in range(0,mat.shape[0]):
        for y in range(0,mat.shape[1]):
            mat[x][y] = random.randrange(1,5)

In [3]:
dummy = np.ndarray((3,3))
FillMatrix(dummy)
vecDum = np.reshape(dummy,-1, order='F')

print("matrix:")
print(dummy)
print("vectorized!")
print(vecDum)

matrix:
[[1. 2. 4.]
 [4. 4. 4.]
 [3. 4. 2.]]
vectorized!
[1. 4. 3. 2. 4. 4. 4. 4. 2.]


In [4]:
pwd

'/Users/matthewmerris/notebooks/doodling'

In [5]:
%cd /Users/matthewmerris/dev/research/tensorly


/Users/matthewmerris/dev/research/tensorly


In [10]:
!echo $PATH
!type pip

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
/Users/matthewmerris/anaconda3/bin:/Users/matthewmerris/anaconda3/condabin:/Users/matthewmerris/.cabal/bin:/Users/matthewmerris/.ghcup/bin:/Users/matthewmerris/.pyenv/plugins/pyenv-virtualenv/shims:/bin:/Users/matthewmerris/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
pip is /Users/matthewmerris/.pyenv/shims/pip


In [6]:
%pip install -e
%cd /Users/matthewmerris/notebooks/doodling

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
/Users/matthewmerris/anaconda3/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
/Users/matthewmerris/notebooks/doodling
